apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - name: jenkins-demo
        image: jenkins-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
